stages:
  - audit
  - test
  - build_pr
  - deploy_pr
  - trash_pr
  - storybook
  - deploy
  - build
  - publish

audit:
  image: node:12.18
  stage: audit
  script:
    - npm i -g npm
    - npm ci
    - npm audit
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'

unit:
  image: node:12.18
  stage: test
  script:
    - npm i -g npm
    - npm ci
    - npm run test
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'

build_pr:
  image: node:12.18
  stage: build_pr
  script:
    - npm i -g npm
    - npm ci
    - npm run storybook:build
  artifacts:
    paths:
      - ./storybook-build
  only:
    - merge_requests

deploy_pr:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy_pr
  dependencies:
    - build_pr
  script:
    - aws s3 sync --delete ./storybook-build s3://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID
  environment:
    name: staging/pr$CI_MERGE_REQUEST_IID
    url: http://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID
    on_stop: trash_pr
  only:
    - merge_requests

trash_pr:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: trash_pr
  when: manual
  script:
    - aws s3 rm --recursive s3://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID/
  environment:
    name: staging/pr$CI_MERGE_REQUEST_IID
    url: http://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID
    action: stop
  only:
    - develop
    - merge_requests

storybook:
  image: node:12.18
  stage: storybook
  script:
    - npm i -g npm
    - npm ci
    - npm run storybook:build
  artifacts:
    paths:
      - ./storybook-build
  only:
    - develop

deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  dependencies:
    - build_develop
  script:
    - aws s3 sync --delete ./storybook-build s3://ui-kit.staging.ekomedia.technology/develop/
  only:
    - develop

build:
  image: node:12.18
  stage: build
  script:
    - npm i -g npm
    - npm ci
    - npm run build
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'
  artifacts:
    # TODO - exclude .git directory from artifacts (console warning given).
    paths:
      - ./

publish:
  image: node:12.18
  stage: publish
  script:
    - npm i -g npm
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'
