stages:
  - audit
  - test
  - build_pr
  - deploy_pr
  - notice_pr
  - trash_pr
  - build_develop
  - deploy_develop
  - notice_develop
  - build
  - deploy
  - notice

audit:
  image: node:12.18
  stage: audit
  script:
    - npm i -g npm
    - npm ci
    - npm audit
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'

unit:
  image: node:12.18
  stage: test
  script:
    - npm i -g npm
    - npm ci
    - npm run test
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'

build_pr:
  image: node:12.18
  stage: build_pr
  script:
    - npm i -g npm
    - npm ci
    - npm run storybook:build
  artifacts:
    paths:
      - ./storybook-build
  only:
    - merge_requests

deploy_pr:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy_pr
  dependencies:
    - build_pr
  script:
    - aws s3 sync --delete ./storybook-build s3://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID
  environment:
    name: staging/pr$CI_MERGE_REQUEST_IID
    url: http://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID
    on_stop: trash_pr
  only:
    - merge_requests

notice_pr:
  image: alpine:latest
  stage: notice_pr
  allow_failure: true
  dependencies:
    - deploy_pr
  script: 
    - apk --no-cache add curl
    - "curl -v -X POST $BOT_SERVER
      -H \"Authorization: Bearer $BOT_TOKEN\"
      -H \"Content-Type: application/json\"
      -d '{\"gid\":\"'$BOT_GROUP_QA_ID'\", \"tid\":\"'$BOT_THREAD_QA_ID'\", \"message\":{\"type\":\"text\",\"data\":\"Feature ready to test!\\n'$CI_MERGE_REQUEST_TITLE'\\nhttp://ui-kit.staging.ekomedia.technology/pr'$CI_MERGE_REQUEST_IID'\"}}'"
  only:
    - merge_requests

trash_pr:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: trash_pr
  when: manual
  script:
    - aws s3 rm --recursive s3://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID/
  environment:
    name: staging/pr$CI_MERGE_REQUEST_IID
    url: http://ui-kit.staging.ekomedia.technology/pr$CI_MERGE_REQUEST_IID
    action: stop
  only:
    - develop
    - merge_requests

build_develop:
  image: node:12.18
  stage: build_develop
  script:
    - npm i -g npm
    - npm ci
    - npm run storybook:build
  artifacts:
    paths:
      - ./storybook-build
  only:
    - develop

deploy_develop:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy_develop
  dependencies:
    - build_develop
  script:
    - aws s3 sync --delete ./storybook-build s3://ui-kit.staging.ekomedia.technology/develop/
  only:
    - develop

notice_develop:
  image: alpine:latest
  stage: notice_develop
  allow_failure: true
  script:
    - apk --no-cache add curl
    - "curl -v -X POST $BOT_SERVER
      -H \"Authorization: Bearer $BOT_TOKEN\"
      -H \"Content-Type: application/json\"
      -d '{\"gid\":\"'$BOT_GROUP_PM_ID'\", \"tid\":\"'$BOT_THREAD_PM_ID'\", \"message\":{\"type\":\"text\",\"data\":\"Ui-Kit environment updated!\\nhttp://ui-kit.staging.ekomedia.technology/develop\"}}'"
  only:
    - develop

build:
  image: node:12.18
  stage: build
  script:
    - npm i -g npm
    - npm ci
    - npm run build
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'
  artifacts:
    paths:
      - ./

publish:
  image: node:12.18
  stage: deploy
  script:
    - npm i -g npm
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'

notice:
  image: alpine:latest
  stage: notice
  allow_failure: true
  dependencies:
    - publish
  script:
    - apk --no-cache add curl
    - "curl -X POST $BOT_SERVER
      -H \"Authorization: Bearer $BOT_TOKEN\"
      -H \"Content-Type: application/json\"
      -d \"{'gid':'\"$BOT_GROUP_RL_ID\"', 'tid':'\"$BOT_THREAD_RL_ID\"', 'message':{'type':'text','data':'Upstra Ui-Kit \"$CI_COMMIT_TAG\"' has been released!'}}\" -i"
  rules:
    - if: '$CI_COMMIT_TAG =~ /(?i)^v[0-9]+\.[0-9]+\.[0-9]+(-rc.[0-9]+)?$/'
