name: Conventional commits

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-checker:
    name: PR title
    runs-on: ubuntu-latest

    steps:
      - uses: EkoCommunications/PRChecks/pr-title@develop
