name: Quality checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  task-checker:
    name: PR check list
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EkoCommunications/PRChecks/task-list@develop
