name: Quality checks

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  task-checker:
    name: PR check list
    runs-on: ubuntu-latest

    steps:
      - uses: EkoCommunications/PRChecks/task-list@develop
